{% set name = "apache-airflow-providers-imap" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b3fae432280a07c9bd9f05eed5b500a6c080905c1403df342305e798dcf87754

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.8.0

test:
  imports:
    - airflow.providers.imap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-imap for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/imap/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-imap/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
