{% set name = "apache-airflow-providers-imap" %}
{% set version = "3.9.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_imap-{{ version }}.tar.gz
  sha256: fa82aaaaa77ed48d9902b88d239e54be9afc935f0632ebf2cee8bc08a50b947b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0

test:
  imports:
    - airflow.providers.imap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-imap for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/imap/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-imap/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
